<?php $code = 'magento_widepay'; ?>
<fieldset class="admin__fieldset payment-method form-list" id="payment_form_<?= /* @noEscape */ $code ?>" style="display:none;">
    <div class="admin__field _required">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_taxvat">
            <span>CPF/CNPJ</span>
        </label>
        <div class="admin__field-control">
            <input type="text" name="payment[magento_widepay_taxvat]" class="admin__control-text input-text admin__control-text required-entry _required" />
        </div>
    </div>
</fieldset>
